### ISSUE TITLE
Remastered version different from the original one

### ISSUE THREAD

**Issue by Benjamin-Loison** [dofera/dofedex#5]
Hello,

I have been looking through your remastered version of 1.37.1 however the js files in the js folder differ from the original remastered distributed by Ankama, what modifications you do ? Could you provide a source code please ?

Furthermore if like these links you have links for the remastered version (because the current links provide only the classic version) it would be great :)

Windows 32-Bit: http://dofusretro.cdn.ankama.com/installers/dofus-retro-win32.zip
Windows 64-Bit: http://dofusretro.cdn.ankama.com/installers/dofus-retro-win64.zip
Linux: http://dofusretro.cdn.ankama.com/installers/dofus-retro-linux64.tar.gz
Mac OS 64-Bit: http://dofusretro.cdn.ankama.com/installers/dofus-retro-mac64.tar.gz

**Comment by dofera** [comment]
Hello @Benjamin-Loison,

I runned a diff between our 1.37.1-remastered and the current one, there is nothing on my side. Can you please provide further informations?

Every versions on this repository are uploaded straight without any modifications. Classic versions are downloaded from [https://download.dofus.com/retro/zip/win32](https://download.dofus.com/retro/zip/win32) whereas remastered versions are zipped from my local Ankama Launcher folder.

Note that since Ankama implemented the launcher, a few minor changes can differ between same release number. For example, the current version number (for linux) is "1.37.1.1256.103-82749dd", as you can see [here](https://launcher.cdn.ankama.com/cytrus.json).

A script was planned to automatically download the sources from the previous link, but it is aborted since Dofera is not active anymore.

**Comment by Benjamin-Loison** [comment]
Using Ankama Launcher (Windows, using WSL, architecture: modern, version: remastered):

C:\Users\USERNAME\AppData\Local\Ankama\Retro\resources\app\retroclient$ find . -type f -exec md5sum {} \; > ../retroHashes.txt
md5sum retroHashes.txt -> 5f94ec58f6a0e08a6a562257ea1cabfd

Using your repository:

dofus-1.37.1-remastered$ find . -type f -exec md5sum {} \; > ../githubHashes.txt
md5sum githubHashes.txt -> 31f9132187b5d2eb1444cdb28cbda9e7

diff retroHashes.txt githubHashes.txt

18542,18543c18542,18543
< af72820343141fb376ee618488fd4e81  ./js/D1Console.js
< 0e20212e90a856c04f37ad3fbe1dbef3  ./js/D1ElectronLauncher.js
---
> e1b3aa3a7dcea1084362688e6c628e80  ./js/D1Console.js
> e029c749198f0f80a976a1b0987b7ac4  ./js/D1ElectronLauncher.js

Maybe you have different js files and Dofus make that in order to trace "on the loose" their obfuscated files ?

Using a JS beautifier (pip install jsbeautifier)

My files:

wc -l *.cjs
 1664 D1Console.cjs
80296 D1ElectronLauncher.cjs

Your repo:

 1598 D1Console.cjs
80464 D1ElectronLauncher.cjs

However here we see that they don't only change a little token but many files (if your really haven't changed these files).

diff dofus-1.37.1-remastered/D1Console.cjs mine/D1Console.cjs | wc -l -> 3 109
diff dofus-1.37.1-remastered/D1ElectronLauncher.cjs mine/D1ElectronLauncher.cjs | wc -l -> 159 097

Archive containing my .js and .cjs and your .cjs:

https://gist.github.com/Benjamin-Loison/7098ed90a06bb52e578fabba3ed01a02/raw/44ba811ab47bfbd6b71daf0aff39065e9e41cb54/Files.zip

**Comment by dofera** [comment]
Sorry, I forgot to precise that I'm running Linux. That's why we are getting different files, check these links:

**Linux**: [https://launcher.cdn.ankama.com/retro/releases/main/linux/5.0_1.37.1.1256.103-82749dd.json](https://launcher.cdn.ankama.com/retro/releases/main/linux/5.0_1.37.1.1256.103-82749dd.json)
`"resources/app/retroclient/js/D1Console.js":{"hash":"12f69e952617d191e3f6f08dbfe8f262427aee86","size":83555}`
_Download D1Console.js_: https://launcher.cdn.ankama.com/retro/hashes/12/12f69e952617d191e3f6f08dbfe8f262427aee86

**Windows**: [https://launcher.cdn.ankama.com/retro/releases/main/windows/5.0_1.37.1.1258.98-82749dd.json](https://launcher.cdn.ankama.com/retro/releases/main/windows/5.0_1.37.1.1258.98-82749dd.json)
`"resources/app/retroclient/js/D1Console.js":{"hash":"e1733773cce8e4aca44afe792c1c117ea2422bc0","size":86874}`
_Download D1Console.js_: https://launcher.cdn.ankama.com/retro/hashes/e1/e1733773cce8e4aca44afe792c1c117ea2422bc0

(Source: [https://launcher.cdn.ankama.com/cytrus.json](https://launcher.cdn.ankama.com/cytrus.json))

**Comment by Benjamin-Loison** [comment]
Thank you for these informations ! (long live to the penguin 🐧)

Ok the additionnal missing to the puzzle was that they use SHA1, otherwise everything is fine, great ! Thanks ! :)
